
format = """$all"""


[git_commit]
commit_hash_length = 4
tag_symbol = "🔖 "
tag_disabled=false

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[🍒 PICKING](bold red)"

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[username]
show_always=true

[time]
disabled=false

[git_branch]
format="on [$symbol$branch$log]($style) "

# [status]
# disabled = false
# format = '[\[$status - $common_meaning\]](green)'
